name: CI

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  build:
    name: Build the wasm package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Download cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            target/
          key: build-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            build-

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Compile with wasm-pack
        run: wasm-pack build --target nodejs

      - name: Compress generated wasm package
        run: |
          mv pkg elm-solve-deps-wasm
          tar czf elm-solve-deps-wasm.tar.gz elm-solve-deps-wasm

      - uses: actions/upload-artifact@v2
        with:
          name: elm-solve-deps-wasm.tar.gz
          path: elm-solve-deps-wasm.tar.gz

  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Check clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -D warnings
        with:
          command: clippy
